In [86]:
from math import *
import numpy as np
import pandas as pd
import csv
import matplotlib.pyplot as plt
import os

In [73]:
# Variables of data to download
d1 = '2018-01-09'
d2 = '2018-02-28'
gr = 'M1'
instrument = 'GBP_USD'
path = '/Users/diegomedina-bernal/Desktop/MadGeniusAlgorithmic/mining-scripts'

In [63]:
!python /Users/diegomedina-bernal/Desktop/MadGeniusAlgorithmic/mining-scripts/oandahist.py 2018-01-09T00:00:00Z 2018-02-28T00:00:00Z H4 GBP_USD

REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-09T00:00:00Z', 'to': '2018-01-09T08:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-09T08:20:00Z', 'to': '2018-01-09T16:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-09T16:40:00Z', 'to': '2018-01-10T01:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-10T01:00:00Z', 'to': '2018-01-10T09:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-10T09:20:00Z', 'to': '2018-01-10T17:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-10T17:40:00Z', 'to': '2018-01-11T02:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-11T02:00:00Z', 'to': '2018-01-11T10:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-11T10:20:00Z', 'to': '2018-01-11T18:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-11T18:40:00Z', 'to': '2018-01-12T03:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-12T03:00:00Z', 'to': '2018-01-12T11:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-12T11:20:00Z', 'to': '2018-01-12T19:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-12T19:40:00Z', 'to': '2018-01-13T04:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-13T04:00:00Z', 'to': '2018-01-13T12:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-13T12:20:00Z', 'to': '2018-01-13T20:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-13T20:40:00Z', 'to': '2018-01-14T05:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-14T05:00:00Z', 'to': '2018-01-14T13:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-14T13:20:00Z', 'to': '2018-01-14T21:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-14T21:40:00Z', 'to': '2018-01-15T06:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-15T06:00:00Z', 'to': '2018-01-15T14:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-15T14:20:00Z', 'to': '2018-01-15T22:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-15T22:40:00Z', 'to': '2018-01-16T07:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-16T07:00:00Z', 'to': '2018-01-16T15:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-16T15:20:00Z', 'to': '2018-01-16T23:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-16T23:40:00Z', 'to': '2018-01-17T08:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-17T08:00:00Z', 'to': '2018-01-17T16:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-17T16:20:00Z', 'to': '2018-01-18T00:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-18T00:40:00Z', 'to': '2018-01-18T09:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-18T09:00:00Z', 'to': '2018-01-18T17:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-18T17:20:00Z', 'to': '2018-01-19T01:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-19T01:40:00Z', 'to': '2018-01-19T10:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-19T10:00:00Z', 'to': '2018-01-19T18:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-19T18:20:00Z', 'to': '2018-01-20T02:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-20T02:40:00Z', 'to': '2018-01-20T11:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-20T11:00:00Z', 'to': '2018-01-20T19:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-20T19:20:00Z', 'to': '2018-01-21T03:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-21T03:40:00Z', 'to': '2018-01-21T12:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-21T12:00:00Z', 'to': '2018-01-21T20:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-21T20:20:00Z', 'to': '2018-01-22T04:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-22T04:40:00Z', 'to': '2018-01-22T13:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-22T13:00:00Z', 'to': '2018-01-22T21:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-22T21:20:00Z', 'to': '2018-01-23T05:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-23T05:40:00Z', 'to': '2018-01-23T14:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-23T14:00:00Z', 'to': '2018-01-23T22:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-23T22:20:00Z', 'to': '2018-01-24T06:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-24T06:40:00Z', 'to': '2018-01-24T15:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-24T15:00:00Z', 'to': '2018-01-24T23:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-24T23:20:00Z', 'to': '2018-01-25T07:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-25T07:40:00Z', 'to': '2018-01-25T16:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-25T16:00:00Z', 'to': '2018-01-26T00:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-26T00:20:00Z', 'to': '2018-01-26T08:40:00Z'}

REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-26T08:40:00Z', 'to': '2018-01-26T17:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-26T17:00:00Z', 'to': '2018-01-27T01:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-27T01:20:00Z', 'to': '2018-01-27T09:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-27T09:40:00Z', 'to': '2018-01-27T18:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-27T18:00:00Z', 'to': '2018-01-28T02:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-28T02:20:00Z', 'to': '2018-01-28T10:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-28T10:40:00Z', 'to': '2018-01-28T19:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-28T19:00:00Z', 'to': '2018-01-29T03:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-29T03:20:00Z', 'to': '2018-01-29T11:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-29T11:40:00Z', 'to': '2018-01-29T20:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-29T20:00:00Z', 'to': '2018-01-30T04:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-30T04:20:00Z', 'to': '2018-01-30T12:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-30T12:40:00Z', 'to': '2018-01-30T21:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-30T21:00:00Z', 'to': '2018-01-31T05:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-31T05:20:00Z', 'to': '2018-01-31T13:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-31T13:40:00Z', 'to': '2018-01-31T22:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-01-31T22:00:00Z', 'to': '2018-02-01T06:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-01T06:20:00Z', 'to': '2018-02-01T14:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-01T14:40:00Z', 'to': '2018-02-01T23:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-01T23:00:00Z', 'to': '2018-02-02T07:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-02T07:20:00Z', 'to': '2018-02-02T15:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-02T15:40:00Z', 'to': '2018-02-03T00:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-03T00:00:00Z', 'to': '2018-02-03T08:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-03T08:20:00Z', 'to': '2018-02-03T16:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-03T16:40:00Z', 'to': '2018-02-04T01:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-04T01:00:00Z', 'to': '2018-02-04T09:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-04T09:20:00Z', 'to': '2018-02-04T17:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-04T17:40:00Z', 'to': '2018-02-05T02:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-05T02:00:00Z', 'to': '2018-02-05T10:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-05T10:20:00Z', 'to': '2018-02-05T18:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-05T18:40:00Z', 'to': '2018-02-06T03:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-06T03:00:00Z', 'to': '2018-02-06T11:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-06T11:20:00Z', 'to': '2018-02-06T19:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-06T19:40:00Z', 'to': '2018-02-07T04:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-07T04:00:00Z', 'to': '2018-02-07T12:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-07T12:20:00Z', 'to': '2018-02-07T20:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-07T20:40:00Z', 'to': '2018-02-08T05:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-08T05:00:00Z', 'to': '2018-02-08T13:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-08T13:20:00Z', 'to': '2018-02-08T21:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-08T21:40:00Z', 'to': '2018-02-09T06:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-09T06:00:00Z', 'to': '2018-02-09T14:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-09T14:20:00Z', 'to': '2018-02-09T22:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-09T22:40:00Z', 'to': '2018-02-10T07:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-10T07:00:00Z', 'to': '2018-02-10T15:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-10T15:20:00Z', 'to': '2018-02-10T23:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-10T23:40:00Z', 'to': '2018-02-11T08:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-11T08:00:00Z', 'to': '2018-02-11T16:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-11T16:20:00Z', 'to': '2018-02-12T00:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-12T00:40:00Z', 'to': '2018-02-12T09:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-12T09:00:00Z', 'to': '2018-02-12T17:20:00Z'}

REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-12T17:20:00Z', 'to': '2018-02-13T01:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-13T01:40:00Z', 'to': '2018-02-13T10:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-13T10:00:00Z', 'to': '2018-02-13T18:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-13T18:20:00Z', 'to': '2018-02-14T02:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-14T02:40:00Z', 'to': '2018-02-14T11:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-14T11:00:00Z', 'to': '2018-02-14T19:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-14T19:20:00Z', 'to': '2018-02-15T03:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-15T03:40:00Z', 'to': '2018-02-15T12:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-15T12:00:00Z', 'to': '2018-02-15T20:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-15T20:20:00Z', 'to': '2018-02-16T04:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-16T04:40:00Z', 'to': '2018-02-16T13:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-16T13:00:00Z', 'to': '2018-02-16T21:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-16T21:20:00Z', 'to': '2018-02-17T05:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-17T05:40:00Z', 'to': '2018-02-17T14:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-17T14:00:00Z', 'to': '2018-02-17T22:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-17T22:20:00Z', 'to': '2018-02-18T06:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-18T06:40:00Z', 'to': '2018-02-18T15:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-18T15:00:00Z', 'to': '2018-02-18T23:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-18T23:20:00Z', 'to': '2018-02-19T07:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-19T07:40:00Z', 'to': '2018-02-19T16:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-19T16:00:00Z', 'to': '2018-02-20T00:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-20T00:20:00Z', 'to': '2018-02-20T08:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-20T08:40:00Z', 'to': '2018-02-20T17:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-20T17:00:00Z', 'to': '2018-02-21T01:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-21T01:20:00Z', 'to': '2018-02-21T09:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-21T09:40:00Z', 'to': '2018-02-21T18:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-21T18:00:00Z', 'to': '2018-02-22T02:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-22T02:20:00Z', 'to': '2018-02-22T10:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-22T10:40:00Z', 'to': '2018-02-22T19:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-22T19:00:00Z', 'to': '2018-02-23T03:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-23T03:20:00Z', 'to': '2018-02-23T11:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-23T11:40:00Z', 'to': '2018-02-23T20:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-23T20:00:00Z', 'to': '2018-02-24T04:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-24T04:20:00Z', 'to': '2018-02-24T12:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-24T12:40:00Z', 'to': '2018-02-24T21:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-24T21:00:00Z', 'to': '2018-02-25T05:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-25T05:20:00Z', 'to': '2018-02-25T13:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-25T13:40:00Z', 'to': '2018-02-25T22:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-25T22:00:00Z', 'to': '2018-02-26T06:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-26T06:20:00Z', 'to': '2018-02-26T14:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-26T14:40:00Z', 'to': '2018-02-26T23:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-26T23:00:00Z', 'to': '2018-02-27T07:20:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-27T07:20:00Z', 'to': '2018-02-27T15:40:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-27T15:40:00Z', 'to': '2018-02-28T00:00:00Z'}
REQUEST: v3/instruments/GBP_USD/candles InstrumentsCandles {'granularity': 'M1', 'includeFirst': True, 'from': '2018-02-28T00:00:00Z', 'to': '2018-02-28T00:00:00Z'}

In [64]:
!ls

DataPrep-1.ipynb                      mining-scripts
FX_NaiveChartPredictions_using_fastai mining-scriptsGBP_USD.H4.csv

In [65]:
df = pd.read_csv('mining-scriptsGBP_USD.H4.csv', names=['time', 'complete', 'open', 'high', 'low', 'close', 'volume'])

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50994 entries, 0 to 50993
Data columns (total 7 columns):
time        50994 non-null object
complete    50994 non-null bool
open        50994 non-null float64
high        50994 non-null float64
low         50994 non-null float64
close       50994 non-null float64
volume      50994 non-null int64
dtypes: bool(1), float64(4), int64(1), object(1)
memory usage: 2.4+ MB

In [67]:
df.head()

                  time  complete     open     high      low    close  volume
0  2018-01-09T00:00:00      True  1.35705  1.35706  1.35686  1.35704      69
1  2018-01-09T00:01:00      True  1.35704  1.35710  1.35703  1.35708      28
2  2018-01-09T00:02:00      True  1.35708  1.35708  1.35698  1.35699      17
3  2018-01-09T00:03:00      True  1.35707  1.35710  1.35703  1.35704      20
4  2018-01-09T00:04:00      True  1.35704  1.35704  1.35688  1.35688      33

In [68]:
df['time'] = pd.DatetimeIndex(df['time'], tz='UTC')
df.head()

,time,complete,open,high,low,close,volume
0,2018-01-09 00:00:00+00:00,True,1.35705,1.35706,1.35686,1.35704,69
1,2018-01-09 00:01:00+00:00,True,1.35704,1.35710,1.35703,1.35708,28
2,2018-01-09 00:02:00+00:00,True,1.35708,1.35708,1.35698,1.35699,17
3,2018-01-09 00:03:00+00:00,True,1.35707,1.35710,1.35703,1.35704,20
4,2018-01-09 00:04:00+00:00,True,1.35704,1.35704,1.35688,1.35688,33

In [69]:
df.set_index('time',inplace=True)
df.head()

,complete,open,high,low,close,volume
time,,,,,,
2018-01-09 00:00:00+00:00,True,1.35705,1.35706,1.35686,1.35704,69
2018-01-09 00:01:00+00:00,True,1.35704,1.35710,1.35703,1.35708,28
2018-01-09 00:02:00+00:00,True,1.35708,1.35708,1.35698,1.35699,17
2018-01-09 00:03:00+00:00,True,1.35707,1.35710,1.35703,1.35704,20
2018-01-09 00:04:00+00:00,True,1.35704,1.35704,1.35688,1.35688,33

In [70]:
# let's now drop the complete column
del df['complete']

In [71]:
df.head()

                              open     high      low    close  volume
time
2018-01-09 00:00:00+00:00  1.35705  1.35706  1.35686  1.35704      69
2018-01-09 00:01:00+00:00  1.35704  1.35710  1.35703  1.35708      28
2018-01-09 00:02:00+00:00  1.35708  1.35708  1.35698  1.35699      17
2018-01-09 00:03:00+00:00  1.35707  1.35710  1.35703  1.35704      20
2018-01-09 00:04:00+00:00  1.35704  1.35704  1.35688  1.35688      33

In [74]:
# Writing to HDF5
os.chdir(path)
h5s = pd.HDFStore(instrument + '_' + gr + '_' + d1[:10] + '_' + d2[:10] + '.h5s', 'w', format='table')
h5s['data'] = df
h5s.close()

In [77]:
df.head()

                              open     high      low    close  volume
time
2018-01-09 00:00:00+00:00  1.35705  1.35706  1.35686  1.35704      69
2018-01-09 00:01:00+00:00  1.35704  1.35710  1.35703  1.35708      28
2018-01-09 00:02:00+00:00  1.35708  1.35708  1.35698  1.35699      17
2018-01-09 00:03:00+00:00  1.35707  1.35710  1.35703  1.35704      20
2018-01-09 00:04:00+00:00  1.35704  1.35704  1.35688  1.35688      33

In [104]:
# Creating new df object
data = df.copy()

In [105]:
data.head()

                              open     high      low    close  volume
time
2018-01-09 00:00:00+00:00  1.35705  1.35706  1.35686  1.35704      69
2018-01-09 00:01:00+00:00  1.35704  1.35710  1.35703  1.35708      28
2018-01-09 00:02:00+00:00  1.35708  1.35708  1.35698  1.35699      17
2018-01-09 00:03:00+00:00  1.35707  1.35710  1.35703  1.35704      20
2018-01-09 00:04:00+00:00  1.35704  1.35704  1.35688  1.35688      33

In [113]:
"""
Indicators
"""

# MA50
ma = 50
data['MA50'] = data['close'].rolling(ma).mean()

# Bollinger Bands
maB = 20
data['BB_20 ma'] = data['close'].rolling(maB).mean()
data['BB_20 sd'] = data['close'].rolling(maB).std()
data['BB_Upper Band'] = data['BB_20 ma'] + (data['BB_20 sd']*2)
data['BB_Lower Band'] = data['BB_20 ma'] - (data['BB_20 sd']*2)
data.drop(['BB_20 sd'], axis=1, inplace=True)

In [114]:
print(data['MA50'].nunique())
print(data['BB_20 ma'].nunique())
print(data['BB_Upper Band'].nunique())
print(data['BB_Lower Band'].nunique())

50156
49264
50620
50620

In [115]:
data.head()

,open,high,low,close,volume,MA50,BB_20 ma,BB_Upper Band,BB_Lower Band
time,,,,,,,,,
2018-01-09 00:00:00+00:00,1.35705,1.35706,1.35686,1.35704,69,NaN,NaN,NaN,NaN
2018-01-09 00:01:00+00:00,1.35704,1.35710,1.35703,1.35708,28,NaN,NaN,NaN,NaN
2018-01-09 00:02:00+00:00,1.35708,1.35708,1.35698,1.35699,17,NaN,NaN,NaN,NaN
2018-01-09 00:03:00+00:00,1.35707,1.35710,1.35703,1.35704,20,NaN,NaN,NaN,NaN
2018-01-09 00:04:00+00:00,1.35704,1.35704,1.35688,1.35688,33,NaN,NaN,NaN,NaN

In [116]:
# Remove the first records which don't have MA calculation
data.drop(data.index[:ma], inplace=True)
data.head()

,open,high,low,close,volume,MA50,BB_20 ma,BB_Upper Band,BB_Lower Band
time,,,,,,,,,
2018-01-09 01:00:00+00:00,1.35663,1.35672,1.35663,1.35667,40,1.356794,1.356855,1.357154,1.356555
2018-01-09 01:01:00+00:00,1.35667,1.35672,1.35667,1.35672,22,1.356787,1.356848,1.357153,1.356543
2018-01-09 01:02:00+00:00,1.35672,1.35675,1.35672,1.35675,16,1.356782,1.356841,1.357148,1.356533
2018-01-09 01:04:00+00:00,1.35668,1.35668,1.35659,1.35660,21,1.356773,1.356826,1.357149,1.356502
2018-01-09 01:05:00+00:00,1.35660,1.35665,1.35660,1.35664,9,1.356768,1.356817,1.357151,1.356482

In [129]:
!mkdir data
!mkdir data/ViewPorts
!mkdir data/ViewPorts/train
!mkdir data/ViewPorts/train/buy | mkdir data/ViewPorts/train/sell | mkdir data/ViewPorts/train/hold

In [133]:
!ls data/ViewPorts/train/

buy  hold sell

In [134]:
from ipywidgets import FloatProgress
from IPython.display import display

# Initialize the size of the ViewPort
size_ViewPort = 60
start_ViewPort = 0
end_ViewPort = size_ViewPort

# Progress bar
f = FloatProgress(min=0, max=(len(data.index)/end_ViewPort))
f.description = 'Progress'
display(f)
# go through the DataFrame and create ViewPorts of 30 records
pic_counter = 0
while end_ViewPort <= len(data.index):
    if (round(data.iloc[end_ViewPort]['close'], 4) - round(data.iloc[end_ViewPort+1]['close'], 4)) > 0:
        data.iloc[start_ViewPort:end_ViewPort].plot(
            kind='line', grid=False, legend=False, figsize=(3, 3)).axis('off')
        PATH = f'{path}/data/ViewPorts/train/buy'
        os.chdir(PATH)
        plt.savefig('buy.' + str(pic_counter) + '.png', dpi=100)
        plt.close()
        pic_counter += 1
        start_ViewPort = end_ViewPort
        end_ViewPort += size_ViewPort
    elif (round(data.iloc[end_ViewPort]['close'], 4) - round(data.iloc[end_ViewPort+1]['close'], 4)) == 0:
        data.iloc[start_ViewPort:end_ViewPort].plot(
            kind='line', grid=False, legend=False, figsize=(3, 3)).axis('off')
        PATH = f'{path}/data/ViewPorts/train/hold'
        os.chdir(PATH)
        plt.savefig('hold.' + str(pic_counter) + '.png', dpi=100)
        plt.close()
        pic_counter += 1
        start_ViewPort = end_ViewPort
        end_ViewPort += size_ViewPort
    else:
        data.iloc[start_ViewPort:end_ViewPort].plot(
            kind='line', grid=False, legend=False, figsize=(3, 3)).axis('off')
        PATH = f'{path}/data/ViewPorts/train/sell'
        os.chdir(PATH)
        plt.savefig('sell.' + str(pic_counter) + '.png', dpi=100)
        plt.close()
        pic_counter += 1
        start_ViewPort = end_ViewPort
        end_ViewPort += size_ViewPort
    f.value += 1
f.bar_style = 'success'

FloatProgress(value=0.0, description='Progress', max=849.0666666666667)

In [135]:
!ls

hold.1.png   hold.204.png hold.351.png hold.492.png hold.648.png hold.767.png
hold.101.png hold.206.png hold.355.png hold.493.png hold.649.png hold.769.png
hold.105.png hold.207.png hold.357.png hold.498.png hold.65.png  hold.770.png
hold.106.png hold.209.png hold.358.png hold.499.png hold.656.png hold.776.png
hold.108.png hold.21.png  hold.359.png hold.514.png hold.657.png hold.778.png
hold.111.png hold.214.png hold.36.png  hold.515.png hold.660.png hold.781.png
hold.113.png hold.218.png hold.362.png hold.52.png  hold.662.png hold.782.png
hold.116.png hold.219.png hold.364.png hold.521.png hold.664.png hold.784.png
hold.118.png hold.22.png  hold.369.png hold.522.png hold.665.png hold.789.png
hold.122.png hold.220.png hold.378.png hold.53.png  hold.666.png hold.79.png
hold.123.png hold.221.png hold.379.png hold.540.png hold.677.png hold.795.png
hold.124.png hold.228.png hold.396.png hold.542.png hold.683.png hold.797.png
hold.127.png hold.23.png  hold.398.png hold.543.png hold.684.png hold.799.png
hold.129.png hold.231.png hold.406.png hold.545.png hold.686.png hold.8.png
hold.133.png hold.235.png hold.415.png hold.555.png hold.687.png hold.801.png
hold.134.png hold.24.png  hold.418.png hold.56.png  hold.69.png  hold.805.png
hold.135.png hold.244.png hold.424.png hold.567.png hold.691.png hold.808.png
hold.136.png hold.25.png  hold.425.png hold.568.png hold.697.png hold.812.png
hold.137.png hold.251.png hold.426.png hold.569.png hold.70.png  hold.822.png
hold.138.png hold.254.png hold.432.png hold.57.png  hold.702.png hold.823.png
hold.140.png hold.257.png hold.439.png hold.572.png hold.705.png hold.824.png
hold.141.png hold.258.png hold.442.png hold.576.png hold.706.png hold.827.png
hold.149.png hold.263.png hold.443.png hold.578.png hold.709.png hold.829.png
hold.162.png hold.270.png hold.444.png hold.585.png hold.711.png hold.830.png
hold.164.png hold.274.png hold.446.png hold.589.png hold.72.png  hold.831.png
hold.166.png hold.275.png hold.447.png hold.59.png  hold.722.png hold.832.png
hold.169.png hold.28.png  hold.45.png  hold.591.png hold.727.png hold.837.png
hold.17.png  hold.282.png hold.450.png hold.598.png hold.728.png hold.843.png
hold.170.png hold.287.png hold.455.png hold.6.png   hold.730.png hold.846.png
hold.172.png hold.302.png hold.458.png hold.600.png hold.731.png hold.848.png
hold.176.png hold.303.png hold.462.png hold.608.png hold.734.png hold.87.png
hold.179.png hold.306.png hold.467.png hold.609.png hold.735.png hold.89.png
hold.18.png  hold.323.png hold.468.png hold.610.png hold.736.png hold.91.png
hold.183.png hold.326.png hold.47.png  hold.613.png hold.747.png hold.92.png
hold.184.png hold.327.png hold.474.png hold.614.png hold.749.png hold.93.png
hold.187.png hold.334.png hold.48.png  hold.622.png hold.753.png hold.94.png
hold.19.png  hold.337.png hold.480.png hold.629.png hold.757.png hold.95.png
hold.2.png   hold.338.png hold.482.png hold.63.png  hold.758.png hold.97.png
hold.20.png  hold.346.png hold.486.png hold.630.png hold.759.png
hold.203.png hold.350.png hold.49.png  hold.637.png hold.764.png

In [138]:
os.chdir('/Users/diegomedina-bernal/Desktop/MadGeniusAlgorithmic/mining-scripts')

In [139]:
!ls

GBP_USD_M1_2018-01-09_2018-02-28.h5s oandahist.py
data